AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # DynamoDB Users Table
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # DynamoDB Posts Table
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Posts
      AttributeDefinitions:
        - AttributeName: postId
          AttributeType: S
      KeySchema:
        - AttributeName: postId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  UsersTableName:
    Description: DynamoDB Users Table Name
    Value: !Ref UsersTable
  PostsTableName:
    Description: DynamoDB Posts Table Name
    Value: !Ref PostsTable

